apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::067100819091:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-EZBF22O9ZETP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
        rolearn: arn:aws:iam::067100819091:role/UdacityFlaskDeployCBKubectlRole
        username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-30T14:39:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1729"
  uid: aef711be-c94e-47c9-a2a8-20a539142f18
